onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
publicHoistPattern:
  - '@langchain/core'
  - '@nuxt/icon'
  - tailwindcss
  - vue
  - zod
